name: Deploy to API VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/harpyadmin/Eksamen2025/Eksamen2025/Eksamen2025
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 0
        path: /home/harpyadmin/Eksamen2025/Eksamen2025/Eksamen2025
    
    - name: Check if package.json exists and install dependencies
      run: |
        if [ -f "package.json" ]; then
          echo "package.json found, checking for changes..."
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi
        else
          echo "No package.json found, skipping npm install"
        fi
    
    - name: Restart PM2 processes
      run: |
        # Check if PM2 is running any processes
        if pm2 list | grep -q "online\|stopped\|errored"; then
          echo "Restarting existing PM2 processes..."
          pm2 restart all
        else
          echo "No PM2 processes found to restart"
        fi
    
    - name: Show PM2 status
      run: pm2 status
